name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      id: build
      run: |
         echo "::set-output name=build::$(echo "hello")"
         docker build . >> test.txt
    - name: check
      env:
        test: "${{ steps.build.outputs.build }}"
      run: |
        echo $test
      
    - name: Send mail
      if: success()
      uses: devellany/send-mail@v1.0.2
      with:
    # mail server settings
       host: smtp.gmail.com
       port: 465
    # user credentials
       account: ${{ secrets.EMAIL_USERNAME }}
       password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
       from: ${{ secrets.EMAIL_USERNAME }}
       subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }} 
    # email body as text
       body: file://test.txt
       #html_body: file://test.html
       #attachments: test.txt
       to: prudhvireddy987@gmail.com
    # from email name
       
    
    
    
       
       
