name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: tetst
      run: echo "hello"
    
    - name: email-body
      uses: dawidd6/action-send-mail@v2
      id: tests
      run: |
        awk  '/1) Webchat Ping/,/(Results)/' test.txt > Failed-tests.txt
        grep Passing: test.txt >> passed-results.txt 
        sed -i '1d' passed-results.txt
        cat passed-results.txt | awk '{print $2,$3}' > passed-test.txt
        cat passed-test.txt
        echo "::set-output name=passing::$(cat passed-test.txt)"
        grep Failing: test.txt >> failed-results.txt 
        sed -i '1d' failed-results.txt
        echo "::set-output name=failed::$(cat failed-results.txt)"
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }} and out
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} and ${{ steps.tests.outputs.passing }}, ${{ steps.tests.outputs.failed }} 
          to: prudhvi.reddy@betaque.com
          from: nayan
          attachments: test.txt
      
    
