name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      id: build
      run: |
         echo "::set-output name=build::$(echo "hello")"
         docker build . >> test.txt
    - name: check
      env:
        test: "${{ steps.build.outputs.build }}"
      run: |
        echo $test
      
    - name: Send mail
      if: success()
      uses: dawidd6/action-send-mail@v2
      with:
    # mail server settings
       server_address: smtp.gmail.com
       server_port: 465
    # user credentials
       username: ${{ secrets.EMAIL_USERNAME }}
       password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
       subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }} 
    # email body as text
       body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} and output is ${{ `cat test.txt` }}
    # comma-separated string, send email to
       to: prudhvireddy987@gmail.com
    # from email name
       from: kprudhvireddy7
    
    
    
       
       
