name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      id: build
      run: echo "::set-output name=FOO::$(echo "hello")"
    - name: check
      env:
        test: ${{join(steps.build.outputs.FOO)}}
      run: |
        echo test
      
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
    # mail server settings
       server_address: smtp.gmail.com
       server_port: 465
    # user credentials
       username: ${{ secrets.EMAIL_USERNAME }}
       password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
       subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # email body as text
       body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    # comma-separated string, send email to
       to: prudhvireddy987@gmail.com
    # from email name
       from: kprudhvireddy7
    
    
    
       
       
